name: Publish Modpack

on:
  push:
    paths:
      - 'manifest.json'
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from manifest.json
        id: extract
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          NAME=$(jq -r '.name' manifest.json)
          echo "MODPACK_VERSION=$VERSION" >> $GITHUB_ENV
          echo "MODPACK_NAME=$NAME" >> $GITHUB_ENV

      - name: Create zip file
        run: |
          zip -r satiscreate-${MODPACK_VERSION}.zip manifest.json overrides/

      - name: Publish to CurseForge and GitHub
        uses: Kira-NT/mc-publish@v3
        with:
          curseforge-id: ${{ secrets.CF_PROJECT_ID }}
          curseforge-token: ${{ secrets.CF_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: satiscreate-${{ env.MODPACK_VERSION }}.zip
          name: "SatisCreate v${{ env.MODPACK_VERSION }}"
          version: v${{ env.MODPACK_VERSION }}
          version-type: release
          changelog: "Release v${{ env.MODPACK_VERSION }}"
          loaders: curseforge_modpack
          game-versions: |
            1.20.1
