name: Build and Upload using manifest version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Extract version from manifest.json
      id: get_version
      run: |
        VERSION=$(jq -r '.version' satiscreate/manifest.json)
        echo "MODPACK_VERSION=$VERSION" >> $GITHUB_ENV
        echo "version: $VERSION"

    - name: Create ZIP file
      run: |
        cd satiscreate
        zip -r ../satiscreate-${MODPACK_VERSION}.zip .

    - name: Upload to CurseForge
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        CF_PROJECT_ID: ${{ secrets.CF_PROJECT_ID }}
      run: |
        curl -X POST \
          -H "x-api-key: $CF_API_KEY" \
          -F "file=@satiscreate-${MODPACK_VERSION}.zip" \
          https://minecraft.curseforge.com/api/projects/$CF_PROJECT_ID/upload-file
