name: Release Modpack

on:
  push:
    paths:
      - 'manifest.json'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 태그 정보를 가져오기 위해 전체 히스토리를 가져옴

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: sudo apt-get install -y jq zip

      - name: Extract version from manifest.json
        id: version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        
      - name: Install Go and packwiz
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        
      - run: go install github.com/packwiz/packwiz@latest
        
      - name: Create .zip
        run: |
          zip -r SatisCreate-${{ steps.version.outputs.VERSION }}.zip manifest.json overrides modlist.html

      - name: Import to packwiz format
        run: |
          [ -f pack.toml ] || packwiz curseforge import satiscreate-${{ env.MODPACK_VERSION }}.zip
          packwiz modrinth export -o SatisCreate-${{ steps.version.outputs.VERSION }}.mrpack

      - name: Generate changelog since last release
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          LOG=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s" || echo "Initial release.")
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish to all platforms with mc-publish
        uses: Kira-NT/mc-publish@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          curseforge-id: ${{ secrets.CF_PROJECT_ID }}
          curseforge-token: ${{ secrets.CF_API_KEY }}
          modrinth-id: ${{ secrets.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            SatisCreate-${{ env.MODPACK_VERSION }}.zip
            SatisCreate-${{ env.MODPACK_VERSION }}.mrpack
          name: "SatisCreate v${{ env.MODPACK_VERSION }}"
          version: v${{ env.MODPACK_VERSION }}
          version-type: release
          changelog: ${{ steps.changelog.outputs.CHANGELOG }}
          loaders: |
              forge
              curseforge_modpack
          game-versions: |
              1.20.1
    